trigger:
  branches:
    include:
      - '*'

pr:
  branches:
    exclude:
      - '*'
pool:
  name: 'DEFRA-COMMON-UBUNTU-SSV5'

resources:
  repositories:
    - repository: ipaffs-infra
      type: github
      endpoint: DEFRA
      name: DEFRA/ipaffs-infra
      ref: refs/heads/main

variables:
  - group: "DEV"
  - group: "LowerEnvs"
  - name: serviceName
    value: redirect-handler
  - name: nodeVersion
    value: 24.13.1
  - name: dockerFile
    value: Dockerfile

stages:
  - stage: BuildService
    displayName: Build Service
    jobs:
      - job: BuildNodeProject
        displayName: Build Node Project
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: ${{ variables.nodeVersion }}
              addToPath: true
            displayName: Install Node and NPM and add to path

          - script: npm  ci
            displayName: 'Install dependencies and build'

          - template: /pipelines/steps/build-container-image.yaml@ipaffs-infra
            parameters:
              dockerFile: ${{ variables.dockerFile }}
              directory: .
              imageName: ${{ variables.serviceName }}




